### ISSUE TITLE
Which python version are you using?

### ISSUE THREAD

**Issue by momokinou** [wajili/SimpleMMO-fully-automatic-bot#2]
Hi :D
I can't install pytorch 1.9.1+cu102 with my python version

(conda install pytorch==1.9.1 torchvision==0.8.2 torchaudio==0.9.1 cudatoolkit=11.3 -c pytorch -c conda-forge)

Thanks

**Comment by momokinou** [comment]
I tried all the latest versions and it's starting.

**Comment by wajili** [comment]
Thanks for the feedback.
This code is relatively simple and the latest version will do. Just pay attention to the version of chrome.
Make sure there is an unknown folder under the simmmobot path, it doesn’t matter if it is empty.
Also update these files.
________________________________
发件人: momokinou ***@***.***>
发送时间: 2023年4月1日 0:50
收件人: wajili/SimpleMMO-fully-automatic-bot ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [wajili/SimpleMMO-fully-automatic-bot] Which python version are you using? (Issue #2)


Closed #2<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwajili%2FSimpleMMO-fully-automatic-bot%2Fissues%2F2&data=05%7C01%7Cm216974%40hiroshima-u.ac.jp%7C097c6d9c8373471ef0d608db31ffb4fe%7Cc40454ddb2634926868d8e12640d3750%7C1%7C0%7C638158746534096663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=waFbntlGSM6OUOmoXf8EgIFuhtWUEITdq%2BsA%2BKaW%2BU0%3D&reserved=0> as completed.

―
