### ISSUE TITLE
Got banned for automation

### ISSUE THREAD

**Issue by momokinou** [wajili/SimpleMMO-fully-automatic-bot#3]
Hi 
I got banned while using it.
Any tips on how to not be banned?

Thanks.

**Comment by xKeksbyte** [comment]
iq?
dont step 24/7 dont get into top 3 leaderboard, make pauses
Dont step over 2k / day 
anyway its patched (you need to fix it yourself, wont release it since it isnt hard, also added event support)
my bot acc is already level 4000 in 1.5weeks so

**Comment by momokinou** [comment]
Patched a few things. Works fine but yeah, no more than 2/3k steps a day.
